name: cfn_nag-updater

on: repository_dispatch

env:
  docker_org: stelligent

jobs:
  update_cfn_nag:
    name: Update cfn_nag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Checkout cfn_nag repo
        uses: actions/checkout@v2
        with:
          repository: pshelby/cfn_nag
          path: cfn_nag
      - name: Setup cfn_nag repo
        run: |
          git -C cfn_nag fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config --global user.email "build@build.com"
          git config --global user.name "build"
      - name: Update versions and sha256
        run: |
          bash ./.github/scripts/update_cfn_nag_formula_version.sh
          rm -rf cfn_nag
        env:
          ORG: pshelby
      - name: Commit
        run: |
          git diff
          git add .
          git commit --allow-empty -m "auto-update cfn_nag versions and sha256"
          git push
